name: Greetings

on: [pull_request, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: 'Welcome to the concurrent-priority-worker-queue repository! Thank you for reporting a bug to us, and I hope you continue to do so in the future.'
        pr-message: 'Thank you for contributing to the concurrent-priority-worker-queue repository!'
